name: Build Injector Local
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build for Android arm64
        run: |
          # Компилируем твой локальный linject.c
          $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang \
          --target=aarch64-linux-android24 \
          --sysroot=$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          -O2 -static linject.c -o injector

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: injector
          path: injector
          
