name: Build Linject
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with NDK
        run: |
          $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/clang \
          --target=aarch64-linux-android24 \
          --sysroot=$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          -Wall -O2 linject.c -o linject

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: linject-binary
          path: linject
          
